# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cae2148c1153d1281d9de9c32cad2b924669b8412bc4387effd53516f8f360e7f2b23e7ca18b466324afeb7c76a142191dc48b057202d4c661585dde07ad24c

test:
  secret_key_base: f5d3db1de5a78480a72b131c4cf9977ba6d6a9a64f40af19726e3afa74aa5f4da50a528133051ae6fe488cd4a17af5adc72c54ec4db2013d2dfba486f45f5834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
